syntax = "proto3";

package chitchat;

//the ;chitchat part renames the Go package to chitchat instead of grpc which
//would clash with the real package. 

option go_package = "github.com/augustersej123/ChitChat/grpc;chitchat";

service ChitChat{
    // Server streaming: Client joins, then receives broadcasts on this stream
    rpc Join(JoinRequest) returns (stream ChatMessage);
    // Unary: Send one chat message
    rpc Publish(PublishRequest) returns (PublishResponse);
    // Unary: leave the chat
    rpc Leave(LeaveRequest) returns (LeaveResponse);
}

message JoinRequest {
    string participant = 1;
    int64 timestamp = 2;
}

message PublishRequest {
    string participant = 1; 
    string content = 2; 
    int64 timestamp = 3;
}

message PublishResponse {
    int64 timestamp = 1;
}

message LeaveRequest {
    string participant = 1;
    int64 timestamp = 2;
}

message LeaveResponse {
    int64 timestamp = 1; 
}

message ChatMessage {
    string sender = 1;
    string content = 2; 
    int64 timestamp = 3; 
}